name: Run bot script

on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run bot script
      run: python bot.py
      env:
        api-key: ${{ secrets.API_KEY }}
        api-secret-key: ${{ secrets.API_SECRET_KEY }}
        access-token: ${{ secrets.ACCESS_TOKEN }}
        access-token-secret: ${{ secrets.ACCESS_TOKEN_SECRET }}
        bearer-token: ${{ secrets.BEARER_TOKEN }}